### ISSUE TITLE
Task description is not showing correctly

### ISSUE THREAD

**Issue by Madouc** [fibasile/nueval-project#1]
the first task is the same for all weeks (week one)
if a week has a second task (Computer-controlled cutting), it is showing up correctly
machine design has no description
moling and casting has the correct one, all after that have the molding and casting tasks

**Comment by Madouc** [comment]
must be a display bug, if i select machine design, it shows nothing,
is shows the correct tasks for whatever week i select afterwards, but then keeps showing those tasks for subsequently selected weeks.
using chrome on chromeOS

**Comment by fibasile** [comment]
Yes, refresh bug. Fixed in the next release, close it after testing

**Comment by fibasile** [comment]
closing now, reopen if shows up again
