### ISSUE TITLE
Dropped out & Next cycle in local eval - not implemented

### ISSUE THREAD

**Issue by emmapa** [fibasile/nueval-project#13]
I don't know if it's a bug.
Anyhow I decided to open this issue.

I tried to mark a student with "dropped out" and "next cycle",
I got a pop-up window with the following message:

Error
Not implemented yet

**Comment by fibasile** [comment]
Coming soon 👍

**Comment by fibasile** [comment]
Implemented in lastest release, closing now, reopen if it doesn't work!
