### ISSUE TITLE
FAQ is the same for every week.

### ISSUE THREAD

**Issue by Madouc** [fibasile/nueval-project#2]

**Comment by wendwarge** [comment]
Or, quite variable...  

Task: 3D Scanning and Printing

    Design a 3D mould, machine it, and cast parts from it.

**Comment by fibasile** [comment]
Fixed in next release

**Comment by wendwarge** [comment]
Still seeing it today.

**Comment by fibasile** [comment]
I copy and pasted the faqs on the machinable version, missed some. I think I fixed it in the rules. Please check if yaml matches the one you see for each module

**Comment by fibasile** [comment]
closing now, reopen if shows up again
