### ISSUE TITLE
Request global evaluation

### ISSUE THREAD

**Issue by nunuromi** [fibasile/nueval-project#20]
I'm not sure if this is an issue, but I can request the global evaluation for a student even if he didn't present his final project.

**Comment by fibasile** [comment]
We didn't track (even if it's implemented) that student presented the project, for this cycle I guess we'll trust local instructors for this.

**Comment by fibasile** [comment]
Luciana is going to check all the students who have presented. 

I need to add a check before requesting the global eval, or something that says "warning: looks like that this student has not presented the final project"

This means a new box in the Unit view page, that shows the final project presentation status, and possibly the slide and a link.

I'll also add a link to the student's website.

**Comment by fibasile** [comment]
I added the tab to check for final project, I think is ok like this.

Reopen if necessary
