### ISSUE TITLE
Need to see which Fab Lab students are from

### ISSUE THREAD

**Issue by lucianaFL** [fibasile/nueval-project#30]
http://nueval.fabacademy.org/#/apps/manager/evaluations

Since my job is based on assigning students to evaluators, (and not assigning them to their own instructors) I need to see at least the Fab Lab they are coming from. 
For me is crucial to know name, surname and Fab Lab from everyone (students, instructors, evaluators)

next year I guess : ))

**Comment by fibasile** [comment]
This should be ok now.
