### ISSUE TITLE
App List on Main Page not displayed...can't enter the eval process...

### ISSUE THREAD

**Issue by romaindivozzo** [fibasile/nueval-project#35]
Ciao Fiore,

When I log in the app, It say "Hi romaindivozzo!" and that's it. No buttons, nothing to select, blank page like below. Tried on 2 computers with Safari/Chrome/Firefox:

<img width="1440" alt="screen shot 2017-06-29 at 17 32 44" src="https://user-images.githubusercontent.com/5367061/27696277-84a6a39a-5cf1-11e7-8b1f-4c1d76a0399e.png">

Any idea ?

**Comment by fibasile** [comment]
Hi Romain, the problem is you are already registered and assigned with another username

fablabdigiscope

Is this under your control or should I reset it to this other username?

**Comment by romaindivozzo** [comment]
Hi Fiore, it would be better if I could use romaindivozzo instead of fablabdigiscope. I could teach Fabacademy somewhere else than Digiscope one day. If it doesn't take to much time for you to do it, please do it!


Let me know when it is ready,


Thanks a lot,

romain


| ROMAIN DI VOZZO | R&D Engineer at INRIA | Fab Lab Manager | Digital Fabrication | Consulting | Arts | Politics |
| linkedin<https://www.linkedin.com/profile/view?id=302033839&trk=hp-identity-name> |
| fablab digiscope<http://fablabdigiscope.wordpress.com> |
| Romain Di Vozzo personal webpage<http://romaindivozzo.wordpress.com> |
| Ultimaker and Youmagine<https://www.youmagine.com/users/romaindivozzo> |
| Fab Academy project page<http://fabacademy.org/archives/2012/students/di_vozzo.romain/index.html> |
| Speap (Sciences-Po Paris)<http://blogs.sciences-po.fr/speap/promotions/promotion-2012-2013/> |
| AIME (Medialab Sciences-Po Paris)<http://www.modesofexistence.org/#credits> |


________________________________
De : Fiore Basile <notifications@github.com>
Envoyé : jeudi 29 juin 2017 18:30
À : fibasile/nueval-project
Cc : Romain; Author
Objet : Re: [fibasile/nueval-project] App List on Main Page not displayed...can't enter the eval process... (#35)


Hi Romain, the problem is you are already registered and assigned with another username

fablabdigiscope

Is this under your control or should I reset it to this other username?

**Comment by fibasile** [comment]
Done!
