### ISSUE TITLE
Firefox doesn't show the website and Final Project Tab of a student

### ISSUE THREAD

**Issue by nunuromi** [fibasile/nueval-project#38]
When using Firefox the cool tab "WebSite and Final Project" dissapears

<img width="610" alt="captura de pantalla 2017-06-30 a las 16 17 47" src="https://user-images.githubusercontent.com/6595077/27739722-ddec03b4-5daf-11e7-9d7f-8977e890d3a4.png">

No problem for me, I'm using Chrome ;)

**Comment by fibasile** [comment]
That was an error deploying one of the latest version. Change has been reverted and now tab is available. Closing.
