### ISSUE TITLE
Mark as Complete function

### ISSUE THREAD

**Issue by wendwarge** [fibasile/nueval-project#4]
I can mark all as 'complete' and put a student forward for global evaluation without giving any feedback or ticking any boxes or sliding any sliders.

**Comment by wendwarge** [comment]
'mark as complete' overrides the sliders, so you can be 38% on the sliders but still complete for that module. Needs to be a higher %age, like 90 - 100.

**Comment by fibasile** [comment]
Mark as complete now enabled only after you reach 90%, same as when the status "Ready" shows.

**Comment by fibasile** [comment]
closing now, reopen if necessary
