### ISSUE TITLE
FAQ question in Interface and application programming

### ISSUE THREAD

**Issue by nunuromi** [fibasile/nueval-project#42]
The FAQ that appears in this section is part of the 3D printing one:
 Define ‘cannot be made subtractively’

Answer:

That cannot be fabricated with 3 axis limitations OR even if it’s possible to make it, it is too complicated.
<img width="984" alt="captura de pantalla 2017-07-02 a las 9 18 01" src="https://user-images.githubusercontent.com/6595077/27767986-239c30b0-5f08-11e7-809b-a04f86ffb01c.png">

**Comment by emmapa** [comment]
Yep, I got the same.
Working on chrome.

**Comment by fibasile** [comment]
bloody yaml, fixed now
