### ISSUE TITLE
mark student as waiting for fixes

### ISSUE THREAD

**Issue by Madouc** [fibasile/nueval-project#44]
better for the stats that way?

**Comment by fibasile** [comment]
I thought about that but the issue is how to know if instructor is
evaluating or waiting or both.

How do you see implemented? Flag, button ..?

**Comment by Madouc** [comment]
i would say within the current design, another button on the top, next to
graduate and recycle

**Comment by puneethrj** [comment]
While we are at it why not add November eval and January presentation too.

**Comment by fibasile** [comment]
I added the button at the top so students can be marked as waiting for feedback.

The flag is resolved when graduating or recycling

The manager app has a table with all students flagged and count is shown in the home.

Please test and close if it's working for you

**Comment by Madouc** [comment]
Works!

**Comment by Madouc** [comment]
@puneethrj, add a separate issue for suggestions like these
