### ISSUE TITLE
'Have you's' are for students

### ISSUE THREAD

**Issue by wendwarge** [fibasile/nueval-project#6]
Instructor shouldn't be able to tick the have you's - they're for the students.

**Comment by wendwarge** [comment]
As these should be checked throughout academy by students and it's a bit close to the deadline, this cycle they shouldn't be obligatory, but next cycle they would be.

**Comment by fibasile** [comment]
I left the option of editing by the instructor to check them, as an additional way to show the student what he didn't do

**Comment by wendwarge** [comment]
ok

**Comment by emmapa** [comment]
I think the double access (student/instructor) to this section will generate confusion.

and due to the fact that the current students are not going to use this feature and we will see how it works the next year, I would keep this issue open as reminder for 2018.

**Comment by fibasile** [comment]
Update: If you access now the application as a student you can check the boxes and save those, as well as answer to feedback.

**Comment by fibasile** [comment]
Closing now, reopen if needed. Labelling wontfix for future reference.
