### ISSUE TITLE
Machien Design

### ISSUE THREAD

**Issue by wendwarge** [fibasile/nueval-project#8]
I can't save the slider section of Machine Design, so can't mark as complete

**Comment by wendwarge** [comment]
But I can for Mechanical Design - given that they're the same, can we combine them?

**Comment by fibasile** [comment]
I combined the two. For now both have separate tasks with the same lines. Can be edited easily, this is where the source lives:

https://raw.githubusercontent.com/fibasile/nueval-machinable-rules/master/src/machine_unit.yaml

**Comment by fibasile** [comment]
I'm also dropping the double checklist and tasks. Just one task in the new version.

https://raw.githubusercontent.com/fibasile/nueval-machinable-rules/master/src/machine_unit.yaml

**Comment by fibasile** [comment]
Updating the unit lost progress on the people already evaluated for this unit. Not a big deal in the test environment, but we need to be sure to keep the same tasks (or their titles) for the future on a cycle basis.

**Comment by fibasile** [comment]
Closing now, the current version has one task only
