### ISSUE TITLE
Final Project - we need an extra place 

### ISSUE THREAD

**Issue by wendwarge** [fibasile/nueval-project#9]
for commenting on the overall project, video, slide etc. And actually saying whether the project is acceptable/complete/awesome. The Final Project Requirements bit in the assessment doc? this is where the student can confirm that their project is: their own design, includes a fabbed input device and an output device of their own design, includes other components made with additive and subtractive techniques,  includes 2D and 3D design elements .

**Comment by fibasile** [comment]
I added a new unit at the bottom, copying in the Final project requirements parts. With the following outcomes:
- Create a Final project page that documents your project
- Create a Final project slide that showcases your project
- Create a Final project video that shows how your project is working

**Comment by fibasile** [comment]
https://raw.githubusercontent.com/fibasile/nueval-machinable-rules/master/src/project_requirements.yaml

**Comment by wendwarge** [comment]
Re-formatted Final Project Requirements in Assessement doc to suit webapp. ~17 checkboxes for students... now down to nine.

**Comment by fibasile** [comment]
Closing now, reopen if needed
